site_name: tfsumpy Documentation
site_description: Documentation for tfsumpy - Terraform Plan Summary Tool
repo_url: https://github.com/rafaelherik/tfsumpy
repo_name: rafaelherik/tfsumpy

theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Basic Usage: usage/basic_usage.md
    - Advanced Usage: usage/advanced_usage.md
    - Configuration: usage/configuration.md
  - Features:
    - Plan Analysis: features/plan_analysis.md
    - Risk Assessment: features/risk_assessment.md
    - Policy Compliance: features/policy_compliance.md
  - API Reference:
    - Analyzers: api/analyzers.md
    - Reporters: api/reporters.md
    - Models: api/models.md
    - Extending tfsumpy: extending.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [tfsumpy]
          options:
            show_source: true
            show_root_heading: true 